CREATE TABLE MEMBER(
  MEMBER_ID VARCHAR2(15) PRIMARY KEY,
  MEMBER_PWD VARCHAR2(20)NOT NULL,
  MEMBER_NAME VARCHAR2(50) NOT NULL,
  MEMBER_NO VARCHAR2(13) NOT NULL
  CONSTRAINT MEMBER_NO_UK UNIQUE,
  MEMBER_NIK VARCHAR2(20) NOT NULL
  CONSTRAINT MEMBER_NIK_UK UNIQUE,
  MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
  MEMBER_EMAIL VARCHAR2(255) NOT NULL
  CONSTRAINT MEMBER_EMAIL_UK UNIQUE,
  MEMBER_PHONE VARCHAR2(30) NOT NULL
  CONSTRAINT MEMBER_PHONE_UK UNIQUE,
  SIGNUP_DATE DATE DEFAULT SYSDATE NOT NULL,
  CONNECTION CHAR(1) CHECK(CONNECTION IN('Y','N')) NOT NULL
);
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '주민번호';
COMMENT ON COLUMN MEMBER.MEMBER_NIK IS '닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.SIGNUP_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.CONNECTION IS '접속여부';