DROP TABLE MEMBER_MGR CASCADE CONSTRAINTS;

CREATE TABLE MEMBER_MGR (
  USER_ID   VARCHAR2(15),
  CHAT      CHAR(1)  DEFAULT 'Y' CONSTRAINT NN_CHAT NOT NULL,
  LOGIN     CHAR(1) DEFAULT 'Y' CONSTRAINT NN_LOGIN NOT NULL,
  CONSTRAINT CK_CHAT_LOGIN CHECK(CHAT IN ('N','Y')), CHECK(LOGIN IN ('N','Y')),
  CONSTRAINT PK_USERID PRIMARY KEY (USER_ID)
);

COMMENT ON COLUMN MEMBER_MGR.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER_MGR.CHAT IS '채팅가능여부';
COMMENT ON COLUMN MEMBER_MGR.LOGIN IS '로그인가능여부';